#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum Keyword {
    Pass,
    If,
    Else,
    While,
    Try,
    Except,
    Finally,
    Raise,
    Assert,
    TrueLiteral,
    FalseLiteral,
    NoneLiteral,
    Def,
    Class,
    Return,
    For,
    In,
    Is,
    Break,
    Continue,
    And,
    Or,
    Not,
    Elif,
    Import,
    From,
    Global,
    Nonlocal,
    As,
    Lambda,
    With,
    Yield,
    Async,
    Await,
    Del,
    Match,
    Case,
    Type,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TokenKind {
    Name,
    Number,
    String,
    Bytes,
    Newline,
    Indent,
    Dedent,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Dot,
    Ellipsis,
    Colon,
    ColonEqual,
    Equal,
    DoubleEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    NotEqual,
    Comma,
    Plus,
    Minus,
    Arrow,
    Star,
    DoubleStar,
    DoubleSlash,
    Slash,
    SlashEqual,
    PlusEqual,
    MinusEqual,
    StarEqual,
    DoubleStarEqual,
    DoubleSlashEqual,
    PercentEqual,
    Percent,
    Pipe,
    PipeEqual,
    Ampersand,
    AmpersandEqual,
    Caret,
    CaretEqual,
    Tilde,
    LeftShift,
    LeftShiftEqual,
    RightShift,
    RightShiftEqual,
    At,
    AtEqual,
    Semicolon,
    FString,
    Keyword(Keyword),
    EndMarker,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub lexeme: String,
    pub offset: usize,
    pub line: usize,
    pub column: usize,
}

impl Token {
    pub fn new(
        kind: TokenKind,
        lexeme: impl Into<String>,
        offset: usize,
        line: usize,
        column: usize,
    ) -> Self {
        Self {
            kind,
            lexeme: lexeme.into(),
            offset,
            line,
            column,
        }
    }
}
