// Auto-generated by scripts/generate_wasm_env_shim.py.
// Browser wasm host shim for unresolved native-only `env` imports.

const _pyrsWarnedImports = new Set();
function _pyrsWarnOnce(name) { if (_pyrsWarnedImports.has(name)) return; _pyrsWarnedImports.add(name); console.warn(`[pyrs wasm] env import '${name}' is not available in browser host; returning fallback value.`); }

function _pyrsFallback(name) {
  _pyrsWarnOnce(name);
  return 0;
}
