#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

BASELINE_FILE="docs/CLONE_BASELINE.txt"
REPORT_FILE="docs/CLONE_AUDIT.md"

usage() {
  cat <<'EOF'
Usage: scripts/clone_audit.sh [--report] [--check] [--update-baseline]

Modes:
  --report           Print clone summary (default mode)
  --check            Fail if current total clone sites exceeds baseline
  --update-baseline  Rewrite docs/CLONE_BASELINE.txt with current totals

Notes:
  - Counts only textual '.clone(' sites under src/.
  - This is a gate against clone-growth regressions, not the final closure signal.
EOF
}

mode="report"
for arg in "$@"; do
  case "$arg" in
    --report) mode="report" ;;
    --check) mode="check" ;;
    --update-baseline) mode="update-baseline" ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "unknown argument: $arg" >&2
      usage
      exit 2
      ;;
  esac
done

total_clones="$(rg -n '\.clone\(' src | wc -l | tr -d ' ')"
vm_mod_clones="$(rg -n '\.clone\(' src/vm/mod.rs | wc -l | tr -d ' ')"
runtime_mod_clones="$(rg -n '\.clone\(' src/runtime/mod.rs | wc -l | tr -d ' ')"

top_files="$(
  rg -n '\.clone\(' src \
    | cut -d: -f1 \
    | sort \
    | uniq -c \
    | sort -nr \
    | head -n 20
)"

vm_hotspots="$(
  awk '
    /^[[:space:]]*fn[[:space:]]+[A-Za-z0-9_]+/ {name=$2; sub(/\(.*/, "", name)}
    /\.clone\(/ {if (name != "") count[name]++}
    END {for (n in count) printf "%5d %s\n", count[n], n}
  ' src/vm/mod.rs | sort -nr | head -n 25
)"

runtime_hotspots="$(
  awk '
    /^[[:space:]]*pub[[:space:]]*fn[[:space:]]+[A-Za-z0-9_]+/ {name=$3; sub(/\(.*/, "", name)}
    /^[[:space:]]*fn[[:space:]]+[A-Za-z0-9_]+/ {name=$2; sub(/\(.*/, "", name)}
    /\.clone\(/ {if (name != "") count[name]++}
    END {for (n in count) printf "%5d %s\n", count[n], n}
  ' src/runtime/mod.rs | sort -nr | head -n 20
)"

generate_report() {
  cat <<EOF
# Clone Audit Report

Generated by: \`scripts/clone_audit.sh\`

## Snapshot
- Total clone call-sites in \`src/\`: **$total_clones**
- Clone call-sites in \`src/vm/mod.rs\`: **$vm_mod_clones**
- Clone call-sites in \`src/runtime/mod.rs\`: **$runtime_mod_clones**

## Top Files
\`\`\`text
$top_files
\`\`\`

## VM Hotspots (\`src/vm/mod.rs\`)
\`\`\`text
$vm_hotspots
\`\`\`

## Runtime Hotspots (\`src/runtime/mod.rs\`)
\`\`\`text
$runtime_hotspots
\`\`\`
EOF
}

case "$mode" in
  report)
    generate_report
    ;;
  check)
    if [[ ! -f "$BASELINE_FILE" ]]; then
      echo "missing baseline file: $BASELINE_FILE" >&2
      exit 2
    fi
    baseline_total="$(awk -F= '/^total_clones=/{print $2}' "$BASELINE_FILE" | tr -d '[:space:]')"
    baseline_vm_mod="$(awk -F= '/^vm_mod_clones=/{print $2}' "$BASELINE_FILE" | tr -d '[:space:]')"
    baseline_runtime_mod="$(awk -F= '/^runtime_mod_clones=/{print $2}' "$BASELINE_FILE" | tr -d '[:space:]')"
    if [[ -z "$baseline_total" || -z "$baseline_vm_mod" || -z "$baseline_runtime_mod" ]]; then
      echo "invalid baseline contents in $BASELINE_FILE" >&2
      exit 2
    fi
    echo "clone audit baseline: total=$baseline_total vm_mod=$baseline_vm_mod runtime_mod=$baseline_runtime_mod"
    echo "clone audit current:  total=$total_clones vm_mod=$vm_mod_clones runtime_mod=$runtime_mod_clones"
    if (( total_clones > baseline_total )); then
      echo "clone audit failed: total clone sites increased" >&2
      exit 1
    fi
    if (( vm_mod_clones > baseline_vm_mod )); then
      echo "clone audit failed: src/vm/mod.rs clone sites increased" >&2
      exit 1
    fi
    if (( runtime_mod_clones > baseline_runtime_mod )); then
      echo "clone audit failed: src/runtime/mod.rs clone sites increased" >&2
      exit 1
    fi
    echo "clone audit check passed"
    ;;
  update-baseline)
    cat > "$BASELINE_FILE" <<EOF
# Clone-site baseline generated by scripts/clone_audit.sh
total_clones=$total_clones
vm_mod_clones=$vm_mod_clones
runtime_mod_clones=$runtime_mod_clones
EOF
    generate_report > "$REPORT_FILE"
    echo "updated $BASELINE_FILE and $REPORT_FILE"
    ;;
esac

