#!/usr/bin/env python3
"""Generate a browser-local shim for raw wasm `env` imports.

This keeps browser module loading deterministic for wasm bundles that still
expose native-host imports (sqlite/zlib/CPython varargs bridge symbols).
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List, Tuple


WASM_MAGIC = b"\x00asm"


def read_u32_leb(data: bytes, idx: int) -> Tuple[int, int]:
    shift = 0
    out = 0
    while True:
        byte = data[idx]
        idx += 1
        out |= (byte & 0x7F) << shift
        if byte < 0x80:
            return out, idx
        shift += 7
        if shift > 35:
            raise ValueError("invalid LEB128 integer")


def read_name(data: bytes, idx: int) -> Tuple[str, int]:
    size, idx = read_u32_leb(data, idx)
    raw = data[idx : idx + size]
    idx += size
    return raw.decode("utf-8", "replace"), idx


def parse_env_imports(wasm_path: Path) -> Dict[str, List[str]]:
    data = wasm_path.read_bytes()
    if data[:4] != WASM_MAGIC:
        raise ValueError(f"not a wasm module: {wasm_path}")

    idx = 8  # magic + version
    env_funcs: List[str] = []
    env_globals: List[str] = []
    env_memories: List[str] = []
    env_tables: List[str] = []

    while idx < len(data):
        section_id = data[idx]
        idx += 1
        section_len, idx = read_u32_leb(data, idx)
        section_end = idx + section_len

        if section_id != 2:  # import section
            idx = section_end
            continue

        import_count, idx = read_u32_leb(data, idx)
        for _ in range(import_count):
            module_name, idx = read_name(data, idx)
            field_name, idx = read_name(data, idx)
            kind = data[idx]
            idx += 1

            if kind == 0:  # function
                _, idx = read_u32_leb(data, idx)
                if module_name == "env":
                    env_funcs.append(field_name)
            elif kind == 1:  # table
                _, idx = read_u32_leb(data, idx)  # elem type
                limits_flags, idx = read_u32_leb(data, idx)
                _, idx = read_u32_leb(data, idx)  # min
                if limits_flags & 1:
                    _, idx = read_u32_leb(data, idx)  # max
                if module_name == "env":
                    env_tables.append(field_name)
            elif kind == 2:  # memory
                limits_flags, idx = read_u32_leb(data, idx)
                _, idx = read_u32_leb(data, idx)  # min
                if limits_flags & 1:
                    _, idx = read_u32_leb(data, idx)  # max
                if module_name == "env":
                    env_memories.append(field_name)
            elif kind == 3:  # global
                idx += 2  # value type + mutability
                if module_name == "env":
                    env_globals.append(field_name)
            elif kind == 4:  # tag
                _, idx = read_u32_leb(data, idx)  # attr
                _, idx = read_u32_leb(data, idx)  # type
                # no env tags expected currently
            else:
                raise ValueError(f"unknown wasm import kind {kind}")

        idx = section_end

    return {
        "funcs": sorted(set(env_funcs)),
        "globals": sorted(set(env_globals)),
        "memories": sorted(set(env_memories)),
        "tables": sorted(set(env_tables)),
    }


def write_env_shim(env_shim_path: Path, imports: Dict[str, List[str]]) -> None:
    funcs = imports["funcs"]
    globals_ = imports["globals"]
    memories = imports["memories"]
    tables = imports["tables"]

    lines: List[str] = []
    lines.append("// Auto-generated by scripts/generate_wasm_env_shim.py.")
    lines.append("// Browser wasm host shim for unresolved native-only `env` imports.")
    lines.append("")
    lines.append("const _pyrsWarnedImports = new Set();")
    lines.append(
        "function _pyrsWarnOnce(name) {"
        " if (_pyrsWarnedImports.has(name)) return;"
        " _pyrsWarnedImports.add(name);"
        " console.warn(`[pyrs wasm] env import '${name}' is not available in browser host; returning fallback value.`);"
        " }"
    )
    lines.append("")
    lines.append("function _pyrsFallback(name) {")
    lines.append("  _pyrsWarnOnce(name);")
    lines.append("  return 0;")
    lines.append("}")
    lines.append("")

    for name in funcs:
        lines.append(f"export function {name}(..._args) {{")
        lines.append(f"  return _pyrsFallback('{name}');")
        lines.append("}")
        lines.append("")

    for name in globals_:
        lines.append(f"export const {name} = 0;")
    if globals_:
        lines.append("")

    for name in memories:
        lines.append(f"export const {name} = new WebAssembly.Memory({{ initial: 1 }});")
    if memories:
        lines.append("")

    for name in tables:
        lines.append(
            f"export const {name} = new WebAssembly.Table({{ initial: 0, element: 'externref' }});"
        )
    if tables:
        lines.append("")

    env_shim_path.write_text("\n".join(lines), encoding="utf-8")


def rewrite_bindgen_js(bindgen_js_path: Path) -> None:
    original = bindgen_js_path.read_text(encoding="utf-8")
    rewritten = original.replace('from "env"', 'from "./pyrs_env.js"')
    bindgen_js_path.write_text(rewritten, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wasm", required=True, type=Path, help="Path to input wasm binary")
    parser.add_argument(
        "--bindgen-js",
        required=True,
        type=Path,
        help="Path to wasm-bindgen JS entrypoint (pyrs.js)",
    )
    parser.add_argument(
        "--out-shim",
        required=True,
        type=Path,
        help="Path for generated env shim JS file",
    )
    args = parser.parse_args()

    imports = parse_env_imports(args.wasm)
    write_env_shim(args.out_shim, imports)
    rewrite_bindgen_js(args.bindgen_js)

    print(
        f"generated wasm env shim: funcs={len(imports['funcs'])} "
        f"globals={len(imports['globals'])} memories={len(imports['memories'])} "
        f"tables={len(imports['tables'])}"
    )


if __name__ == "__main__":
    main()
